server:
  port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://localhost:8180/auth/realms/bank-system
          jwk-set-uri: http://localhost:8180/auth/realms/bank-system/protocol/openid-connect/certs 