server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s

spring:
  application:
    name: hr-payroll

#Projeto Dependente
#hr-worker:
#  host: http://localhost:8001