
server:
# static port 
  port: 8201

# dynamic port
#  port:${PORT:0}

eureka:
  #for dynamic port
  #instance:
  #  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 

spring:
  
  application:
    name: hr-user

  #config:
  #  import: optional:configserver:http://localhost:8888/


  #Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  
# Usado pelo Actuator
# Para permitir que o atuator atualiza as configurações do 
# Config Server via runtime
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - '*'  
  
